server:
  port: 80

zuul:
  host:
    connect-timeout-millis: 80000
    socket-timeout-millis: 80000
  ribbon:
    eager-load:
      enabled: true
  routes:
    user-service:
      path: /userapi/**
      serviceId: user-service
      sensitiveHeaders:
    order-service:
      path: /orderapi/**
      serviceId: order-service
      sensitiveHeaders: