server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChuanRangSong/spring-cloud-starter
          username: scr0419@outlook.com
          password: scr19910419
          search-paths: config-server/src/main/resources/config
  application:
    name: config-server